services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    networks:
      brabus_net:

networks:
  brabus_net:
    ipam:
      config:
        - subnet: 172.28.0.0/16
