// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson76e781b5DecodeBrabusPkgDto(in *jlexer.Lexer, out *Limits) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "FailLimit":
			out.FailLimit = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76e781b5EncodeBrabusPkgDto(out *jwriter.Writer, in Limits) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"FailLimit\":"
		out.RawString(prefix[1:])
		out.Int(int(in.FailLimit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Limits) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76e781b5EncodeBrabusPkgDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Limits) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76e781b5EncodeBrabusPkgDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Limits) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76e781b5DecodeBrabusPkgDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Limits) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76e781b5DecodeBrabusPkgDto(l, v)
}
func easyjson76e781b5DecodeBrabusPkgDto1(in *jlexer.Lexer, out *Global) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Limits":
			(out.Limits).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76e781b5EncodeBrabusPkgDto1(out *jwriter.Writer, in Global) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Limits\":"
		out.RawString(prefix[1:])
		(in.Limits).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Global) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76e781b5EncodeBrabusPkgDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Global) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76e781b5EncodeBrabusPkgDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Global) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76e781b5DecodeBrabusPkgDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Global) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76e781b5DecodeBrabusPkgDto1(l, v)
}
