// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC3a4bdbeDecodeBrabusPkgDto(in *jlexer.Lexer, out *RAM) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "usage":
			out.Usage = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC3a4bdbeEncodeBrabusPkgDto(out *jwriter.Writer, in RAM) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"usage\":"
		out.RawString(prefix[1:])
		out.String(string(in.Usage))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RAM) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC3a4bdbeEncodeBrabusPkgDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RAM) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC3a4bdbeEncodeBrabusPkgDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RAM) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC3a4bdbeDecodeBrabusPkgDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RAM) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC3a4bdbeDecodeBrabusPkgDto(l, v)
}
