// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package DTO

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson50d358d1DecodeBrabusInternalDTO(in *jlexer.Lexer, out *Metrics) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cpu_usage":
			if in.IsNull() {
				in.Skip()
				out.CPUUsage = nil
			} else {
				in.Delim('[')
				if out.CPUUsage == nil {
					if !in.IsDelim(']') {
						out.CPUUsage = make([]string, 0, 4)
					} else {
						out.CPUUsage = []string{}
					}
				} else {
					out.CPUUsage = (out.CPUUsage)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.CPUUsage = append(out.CPUUsage, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ram_usage":
			out.RAMUsage = string(in.String())
		case "disk_space":
			out.DiskSpace = string(in.String())
		case "disk_usage":
			out.DiskUsage = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson50d358d1EncodeBrabusInternalDTO(out *jwriter.Writer, in Metrics) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cpu_usage\":"
		out.RawString(prefix[1:])
		if in.CPUUsage == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.CPUUsage {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ram_usage\":"
		out.RawString(prefix)
		out.String(string(in.RAMUsage))
	}
	{
		const prefix string = ",\"disk_space\":"
		out.RawString(prefix)
		out.String(string(in.DiskSpace))
	}
	{
		const prefix string = ",\"disk_usage\":"
		out.RawString(prefix)
		out.String(string(in.DiskUsage))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Metrics) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson50d358d1EncodeBrabusInternalDTO(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Metrics) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson50d358d1EncodeBrabusInternalDTO(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Metrics) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson50d358d1DecodeBrabusInternalDTO(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Metrics) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson50d358d1DecodeBrabusInternalDTO(l, v)
}
