// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package DTO

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson50d358d1DecodeBrabusInternalDTO(in *jlexer.Lexer, out *Metrics) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cpu":
			(out.CPU).UnmarshalEasyJSON(in)
		case "ram":
			easyjson50d358d1DecodeBrabusInternalDTO1(in, &out.RAM)
		case "disk":
			(out.Disk).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson50d358d1EncodeBrabusInternalDTO(out *jwriter.Writer, in Metrics) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cpu\":"
		out.RawString(prefix[1:])
		(in.CPU).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"ram\":"
		out.RawString(prefix)
		easyjson50d358d1EncodeBrabusInternalDTO1(out, in.RAM)
	}
	{
		const prefix string = ",\"disk\":"
		out.RawString(prefix)
		(in.Disk).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Metrics) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson50d358d1EncodeBrabusInternalDTO(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Metrics) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson50d358d1EncodeBrabusInternalDTO(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Metrics) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson50d358d1DecodeBrabusInternalDTO(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Metrics) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson50d358d1DecodeBrabusInternalDTO(l, v)
}
func easyjson50d358d1DecodeBrabusInternalDTO1(in *jlexer.Lexer, out *RAM) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "usage":
			out.Usage = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson50d358d1EncodeBrabusInternalDTO1(out *jwriter.Writer, in RAM) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"usage\":"
		out.RawString(prefix[1:])
		out.String(string(in.Usage))
	}
	out.RawByte('}')
}
